version: "3.11"

services:
  opensearch:
    build: .
    container_name: opensearch
    ports:
      - "9200:9200"
      - "9600:9600" # Performance Analyzer
    environment:
      - discovery.type=single-node
      - "DISABLE_SECURITY_PLUGIN=true"

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.9.0
    container_name: opensearch-dashboards
    ports:
      - "5601:5601" # Default port for Dashboards
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    depends_on:
      - opensearch


