"use client";

import { Handle, Node, NodeProps, Position } from "@xyflow/react";
import { useState } from "react";
import { Card, CardContent } from "../ui/card";
import { experimental_useObject as useObject } from "@ai-sdk/react";
import { nodeSchema } from "@/types/schema";
import { generateId } from "ai";
import useStore from "@/store/node-store";
import { AppNode } from "@/store/types";
import { Edge } from "@xyflow/react";

// made to display code generated by ChatGPT.

type CodeNode = Node<{
  explanation: string;
  code: string;
}>;

export function CodeNode({ id, data, isConnectable }: NodeProps<CodeNode>) {
  const [prompt, setPrompt] = useState(data.explanation);
  //   const [option, setOption] = useState("");
  //   code comes in from ChatGPT
  const [code, setCode] = useState(data.code); // string []

  //   if <code> doesn't do well with streaming data, could use loading screen while code completes.
  const [loading, setLoading] = useState(true);
  const { setNodes, setEdges } = useStore();
  const { submit, isLoading, error, object } = useObject({
    id,
    api: "/api/ai",
    schema: nodeSchema,
    onFinish: ({ object }) => {
      const newNodes: AppNode[] = [];
      const newEdges: Edge[] = [];
      console.log(object);
      if (object?.nodes.length) {
        object.nodes.forEach((node) => {
          const newNodeId = generateId();
          const newNode = {
            id: newNodeId,
            type: node.type,
            data: node.data,
            position: { x: 0, y: 0 },
            parentId: id,
          };
          const newEdge = {
            id: `${id}-${newNodeId}`,
            source: id,
            target: newNodeId,
          };
          newNodes.push(newNode);
          newEdges.push(newEdge);
        });
      }
      setNodes(newNodes);
      setEdges(newEdges);
    },
  });
  const handleSubmit = () => {
    // setCode(code);
    // submit({ prompt });
  };
  return (
    <Card className="w-[300px]">
      <CardContent className="flex flex-col gap-2 p-2">
        <h3>Code</h3>
        <pre>
          <code className="overflow-x-auto">{code}</code>
        </pre>
      </CardContent>
      <Handle type="target" position={Position.Top} isConnectable={false} />
      <Handle type="source" position={Position.Bottom} isConnectable={false} />
    </Card>
  );
}
